### ISSUE TITLE
Most current version not available via ansible-galaxy

### ISSUE THREAD

**Issue by Tronde** [Yannik/ansible-role-relaymail#15]
Hello Yannik,  
I've installed your role via ansible-galaxy and recognized that the most current version is not available in galaxy. Last version in galaxy is v2.1.0 from three years ago.

Do you have any plans to update the role in galaxy or do you have abandoned it there?

Regards,  
Tronde

**Comment by Yannik** [comment]
Hi,

I don't recommend using the ansible galaxy repository for security reasons: https://github.com/ansible/ansible/issues/14604
I'd recommend using `src` and `version` to specify a known-good commit hash.

Nonetheless, I have just pushed the latest version to ansible galaxy so that the role is easier to find.

Yannik
